dist: trusty
language: cpp
services: docker

os: linux

cache:
  directories:
    - $HOME/.ccache
    - $HOME/Library/Caches/Homebrew

stages:
  - test # Default stage with job matrix
  - osx

compiler:
  - gcc

env:
  global:
    - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
  matrix:
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="xenial" VALGRIND_TESTS="ON" COMPILE_BINDINGS="ON" FULL_DEPS="ON"
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="xenial" VALGRIND_TESTS="OFF" COMPILE_BINDINGS="ON" FULL_DEPS="ON"
    - TRAVIS_BUILD_TYPE="Release" UBUNTU="bionic" VALGRIND_TESTS="OFF" COMPILE_BINDINGS="ON" FULL_DEPS="ON"
    - TRAVIS_BUILD_TYPE="Debug" UBUNTU="bionic" VALGRIND_TESTS="OFF" COMPILE_BINDINGS="ON" FULL_DEPS="ON"

# ===================
# STAGE: test (linux)
# ===================

before_script:
  - docker pull ubuntu:$UBUNTU

script:
  - >-
    docker run -it \
      -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR \
      -v $HOME/.ccache:$HOME/.ccache \
      -w $TRAVIS_BUILD_DIR \
      --env CC \
      --env CXX \
      --env TRAVIS_BUILD_DIR \
      --env TRAVIS_BUILD_TYPE \
      --env TRAVIS_CMAKE_GENERATOR \
      --env VALGRIND_TESTS \
      --env COMPILE_BINDINGS \
      --env FULL_DEPS \
      ubuntu:$UBUNTU \
      sh .ci/install_debian_and_script.sh

# ==========
# STAGE: osx
# ==========

stage_osx:
  install: &osx_install
    # Setup ccache
    - brew update
    - brew install ccache
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    # Install dependencies
    - brew install ace eigen boost tinyxml swig qt5 gsl pkg-config jpeg sqlite tinyxml
    - export Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
  script: &osx_script
    - cd $TRAVIS_BUILD_DIR/.ci
    - sh ./script.sh

# ======================
# BUILD JOBS FROM STAGES
# ======================

jobs:
  include:
    # ---------
    # STAGE OSX
    # ---------
    - &osx_template
      stage: osx
      os: osx
      osx_image: xcode9.4
      before_install: skip
      install: *osx_install
      before_script: skip
      script: *osx_script
      after_failure: skip
      after_success: skip
      after_script: skip
      env:
        TRAVIS_CMAKE_GENERATOR="Xcode"
        TRAVIS_BUILD_TYPE="Debug"
        VALGRIND_TESTS="OFF"
        COMPILE_BINDINGS="OFF"
        FULL_DEPS="OFF"
    - <<: *osx_template
      compiler: clang
      env:
        TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
        TRAVIS_BUILD_TYPE="Debug"
        VALGRIND_TESTS="OFF"
        COMPILE_BINDINGS="OFF"
        FULL_DEPS="OFF"


notifications:
  email:
    - pegua1@gmail.com
