language: cpp

compiler:
  - gcc
  - clang

env:
  - IDYNTREE_TRAVIS_BUILD_TYPE=Debug, IDYNTREE_USES_ICUB=TRUE
  - IDYNTREE_TRAVIS_BUILD_TYPE=Release, IDYNTREE_USES_ICUB=TRUE
  - IDYNTREE_USES_ICUB=
  FALSE

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update
  - sudo apt-get install -qq libeigen3-dev libboost-system-dev libboost-thread-dev libtinyxml-dev
  - sudo apt-get --force-yes install yarp
  - if [ $IDYNTREE_USES_ICUB ]; then sudo apt-get --force-yes install icub; fi
  - sudo apt-get install cmake

before_script:
  - cmake --version
  - cd ..
  # Build orocos_kinematics_dynamics and install it in a local directory
  - git clone https://github.com/orocos/orocos_kinematics_dynamics
  - cd orocos_kinematics_dynamics
  - cd orocos_kdl
  - mkdir build
  - cd build
  - mkdir local_install
  - cmake -DCMAKE_INSTALL_PREFIX="./local_install" -DCMAKE_BUILD_TYPE=${IDYNTREE_TRAVIS_BUILD_TYPE} ..
  - make
  - make install
  - cd ../../..
  # Build kdl_codyco and install it in a local directory
  - git clone https://github.com/traversaro/kdl_codyco
  - cd kdl_codyco
  - mkdir build
  - cd build
  - mkdir local_install
  - cmake -DCMAKE_INSTALL_PREFIX="./local_install" -DCMAKE_BUILD_TYPE=${IDYNTREE_TRAVIS_BUILD_TYPE} ..
  - make
  - make install
  - cd ../..
  # Build kdl_format_io and install it in a local directory
  - sudo chmod +x ./iDynTree/.travis/build_urdfdom
  - ./iDynTree/.travis/build_urdfdom
  - git clone https://github.com/traversaro/kdl_format_io
  - cd kdl_format_io
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${IDYNTREE_TRAVIS_BUILD_TYPE} ..
  - make
  - sudo make install
  - cd ../..
  # Build and install YCM
  - git clone https://github.com/robotology/ycm.git
  - cd ycm
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  # Prepare iDynTree build
  - cd iDynTree
  - mkdir build
  - cd build
  - if[ $IDYNTREE_USES_ICUB ]; then cmake -DCMAKE_BUILD_TYPE=${IDYNTREE_TRAVIS_BUILD_TYPE} -DIDYNTREE_BUILD_TESTS:BOOL=ON .. ; fi
  - if[ "$IDYNTREE_USES_ICUB" = "FALSE" ]; then cmake -DCMAKE_BUILD_TYPE=${IDYNTREE_TRAVIS_BUILD_TYPE} -DIDYNTREE_USES_ICUB:BOOL=OFF .. ; fi
  
script:
  - make
  - sudo make install
  - if[ $IDYNTREE_USES_ICUB ]; then ctest -V ; fi

notifications:
  email:
    - pegua1@gmail.com
