language: cpp

compiler:
  - gcc
  - clang

env:
# set the CMAKE_PREFIX_PATH enviroment variable to get software installed by the superbuild
  - TRAVIS_BUILD_TYPE=Debug, TRAVIS_CMAKE_GENERATOR="Unix Makefiles", CMAKE_PREFIX_PATH="/home/travis/build/robotology/codyco-superbuild/build/install"
  - TRAVIS_BUILD_TYPE=Release, TRAVIS_CMAKE_GENERATOR="Unix Makefiles", CMAKE_PREFIX_PATH="/home/travis/build/robotology/codyco-superbuild/build/install"

matrix:
  allow_failures:
    - compiler: clang

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install -qq libeigen3-dev libboost-system-dev libboost-thread-dev libboost-test-dev valgrind liblua5.1-0-dev lua5.1 swig python-dev
  - sudo apt-get --force-yes install icub-common
  - sudo apt-get install cmake

before_script:
  # workaround around opencv linking problem in clang:
  # http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394
  - sudo ln /dev/null /dev/raw1394
  - cmake --version
  - cd ..
  # use superbuild for getting iDynTree dependencies
  - git clone https://github.com/robotology/codyco-superbuild
  - cd codyco-superbuild
  # install dependencies using the codyco-superbuild script
  - chmod +x ./.ci/travis-deps.sh
  - sh .ci/travis-deps.sh
  - mkdir build
  - cd build
  # using the YCM_EP_MAINTAINER_MODE variable to enable the subproject-dependees target
  - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DYCM_EP_MAINTAINER_MODE:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - make iDynTree-dependees 
  - pwd
  - cd ../..
  # deal with TinyXML linking problems
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/robotology/codyco-superbuild/build/install/lib
  - ls /home/travis/build/robotology/codyco-superbuild/build/install/lib
  - echo $LD_LIBRARY_PATH
  - sudo ldconfig
  # Prepare iDynTree build
  - cd idyntree
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DIDYNTREE_COMPILE_TESTS:BOOL=ON -DIDYNTREE_COMPILE_BINDINGS:BOOL=ON -DIDYNTREE_USES_PYTHON:BOOL=ON -DIDYNTREE_USES_LUA:BOOL=ON -DIDYNTREE_RUN_VALGRIND_TESTS:BOOL=ON -DCODYCO_TRAVIS_CI:BOOL=ON -DSTANDARD_FIND_MODULE_DEBUG:BOOL=ON ..

script:
  - make
  - sudo make install
  - ctest -VV -R Python

notifications:
  email:
    - pegua1@gmail.com
